image: "rustlang/rust:nightly"

test:
  script:
    - rustc --version && cargo --version
    - cargo test --all --release
  tags: ["linux"]

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - cargo/
