[package]
authors = ["Scott Minor <minor@minorhacks.com>"]
edition = "2018"
name = "advent_2020"
version = "0.1.0"

[features]
expensive_tests = []

[dependencies]
itertools = "0.9.0"
regex = "1.4.2"
ndarray = "0.14.0"
scan_fmt = "0.2.5"
thiserror = "1.0.22"
