[package]
authors = ["Scott Minor <minor@minorhacks.com>"]
edition = "2018"
name = "advent_2020"
version = "0.1.0"

[features]
expensive_tests = []

[dependencies]
itertools = "0"
regex = "1"
ndarray = "0"
scan_fmt = "0"
thiserror = "1"
