on: [pull_request]

name: check_rust

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    steps:
      - uses: actions/checkout@v2
      - name: Log tool versions
        run: rustc --version && cargo --version
      - name: Run all tests
        run: cargo test --all --release --features expensive_tests --color=always

  clippy:
    name: lint
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    steps:
      - uses: actions/checkout@v2
      - name: Log tool versions
        run: rustc --version && cargo --version
      - name: Lint
        run: cargo clippy --all-features --color=always -- -D warnings
